#!/usr/bin/sh

profiles_dir="$HOME/.local/share/browser-profiles"
[ ! -e "$profiles_dir" ] && mkdir -p "$profiles_dir"

run() {
    browser="$1"
    profile_dir="$2"

    case $browser in
        qutebrowser) qutebrowser --restore default -B "$profile_dir"
            ;;
        firefox*)
            eval "$browser" --profile "$profile_dir"
            ;;
    esac
}

# config is file with lines formatted as follows `profile=browser`
config=${BROWSER_CONFIG:-"$HOME/.config/browser-profiles/config"}
[ ! -e "$config" ] && mkdir -p $(dirname "$config") && touch "$config"

while IFS= read -r line; do
    read profile browser <<< $(tr '=' ' ' <<< "$line")

    if [[ "$profile" == "$1" ]]; then
        profile_dir="$profiles_dir/$profile"
        [ ! -e "$profile_dir" ] && mkdir -p "$profile_dir"
        run "$browser" "$profile_dir"
        exit 0
    fi
done < "$config"

echo "can't find profile $1"
rmdir "$profile_dir"
exit 1
